// <auto-generated />
using Allowed.Telegram.Bot.Sample.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Allowed.Telegram.Bot.Sample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221219202816_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Allowed.Telegram.Bot.Sample.DbModels.Allowed.ApplicationTgBot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_telegram_bots");

                    b.ToTable("telegram_bots", (string)null);
                });

            modelBuilder.Entity("Allowed.Telegram.Bot.Sample.DbModels.Allowed.ApplicationTgBotUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BotBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("bot_blocked");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<int>("TelegramBotId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_bot_id");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_user_id");

                    b.HasKey("Id")
                        .HasName("pk_telegram_bot_users");

                    b.HasIndex("TelegramBotId")
                        .HasDatabaseName("ix_telegram_bot_users_telegram_bot_id");

                    b.HasIndex("TelegramUserId")
                        .HasDatabaseName("ix_telegram_bot_users_telegram_user_id");

                    b.ToTable("telegram_bot_users", (string)null);
                });

            modelBuilder.Entity("Allowed.Telegram.Bot.Sample.DbModels.Allowed.ApplicationTgBotUserRole", b =>
                {
                    b.Property<int>("TelegramBotUserId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_bot_user_id");

                    b.Property<int>("TelegramRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_role_id");

                    b.HasKey("TelegramBotUserId", "TelegramRoleId")
                        .HasName("pk_telegram_bot_user_roles");

                    b.HasIndex("TelegramRoleId")
                        .HasDatabaseName("ix_telegram_bot_user_roles_telegram_role_id");

                    b.ToTable("telegram_bot_user_roles", (string)null);
                });

            modelBuilder.Entity("Allowed.Telegram.Bot.Sample.DbModels.Allowed.ApplicationTgRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_telegram_roles");

                    b.ToTable("telegram_roles", (string)null);
                });

            modelBuilder.Entity("Allowed.Telegram.Bot.Sample.DbModels.Allowed.ApplicationTgUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_telegram_users");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ix_telegram_users_telegram_id");

                    b.HasIndex("Username")
                        .HasDatabaseName("ix_telegram_users_username");

                    b.ToTable("telegram_users", (string)null);
                });

            modelBuilder.Entity("Allowed.Telegram.Bot.Sample.DbModels.UserFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("integer")
                        .HasColumnName("telegram_user_id");

                    b.Property<string>("Type")
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_user_files");

                    b.HasIndex("TelegramUserId")
                        .HasDatabaseName("ix_user_files_telegram_user_id");

                    b.ToTable("user_files", (string)null);
                });

            modelBuilder.Entity("Allowed.Telegram.Bot.Sample.DbModels.Allowed.ApplicationTgBotUser", b =>
                {
                    b.HasOne("Allowed.Telegram.Bot.Sample.DbModels.Allowed.ApplicationTgBot", null)
                        .WithMany()
                        .HasForeignKey("TelegramBotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_bot_users_telegram_bots_application_tg_bot_id");

                    b.HasOne("Allowed.Telegram.Bot.Sample.DbModels.Allowed.ApplicationTgUser", null)
                        .WithMany()
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_bot_users_telegram_users_application_tg_user_id");
                });

            modelBuilder.Entity("Allowed.Telegram.Bot.Sample.DbModels.Allowed.ApplicationTgBotUserRole", b =>
                {
                    b.HasOne("Allowed.Telegram.Bot.Sample.DbModels.Allowed.ApplicationTgBotUser", null)
                        .WithMany()
                        .HasForeignKey("TelegramBotUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_bot_user_roles_telegram_bot_users_application_tg_b");

                    b.HasOne("Allowed.Telegram.Bot.Sample.DbModels.Allowed.ApplicationTgRole", null)
                        .WithMany()
                        .HasForeignKey("TelegramRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telegram_bot_user_roles_telegram_roles_application_tg_role_");
                });

            modelBuilder.Entity("Allowed.Telegram.Bot.Sample.DbModels.UserFile", b =>
                {
                    b.HasOne("Allowed.Telegram.Bot.Sample.DbModels.Allowed.ApplicationTgUser", "TelegramUser")
                        .WithMany("UserFiles")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_files_telegram_users_telegram_user_id");

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("Allowed.Telegram.Bot.Sample.DbModels.Allowed.ApplicationTgUser", b =>
                {
                    b.Navigation("UserFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
